---
abstract: 'Adding keywords to perl, in perl'
author:
  - 'Matt S Trout - <mst@shadowcat.co.uk> - original author'
build_requires:
  B::Hooks::OP::Check: 0.10
  ExtUtils::MakeMaker: 6.42
configure_requires:
  B::Hooks::OP::Check: 0.10
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Declare
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::EndOfScope: 0.05
  B::Hooks::OP::Check: 0.10
  Scalar::Util: 0
  Sub::Name: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.005003
