---
abstract: 'Adding keywords to perl, in perl'
author:
  - 'Matt S Trout - <mst@shadowcat.co.uk> - original author'
build_requires:
  B::Hooks::OP::Check: 0.19
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
configure_requires:
  B::Hooks::OP::Check: 0.19
  ExtUtils::Depends: 0.302
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Declare
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::EndOfScope: 0.05
  B::Hooks::OP::Check: 0.19
  Scalar::Util: 1.11
  Sub::Name: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/p5sagit/Devel-Declare.git
version: 0.006013
