--- 
abstract: ''
author: Matt S Trout - <mst@shadowcat.co.uk>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Devel-Declare
no_index: 
  directory: 
    - inc
    - t
requires: 
  Scalar::Util: 0
  perl: 5.8.1
version: 0.001005
