---
abstract: 'Adding keywords to perl, in perl'
author:
  - 'Matt S Trout - <mst@shadowcat.co.uk> - original author'
build_requires:
  B::Hooks::OP::Check: '0.19'
  Test::More: '0.88'
  Test::Requires: '0'
configure_requires:
  B::Hooks::OP::Check: '0.19'
  ExtUtils::Depends: '0.302'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Declare
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::EndOfScope: '0.05'
  B::Hooks::OP::Check: '0.19'
  Scalar::Util: '1.11'
  Sub::Name: '0'
  perl: '5.008001'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Devel-Declare
  repository: git://git.shadowcat.co.uk/p5sagit/Devel-Declare.git
version: '0.006017'
